// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package author

import (
	"gobook/src/author/delivery/http"
	author2 "gobook/src/author/repository"
	author3 "gobook/src/author/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeService(db *gorm.DB) *author.AuthorHandler {
	authorRepository := author2.NewAuthorRepository(db)
	authorService := author3.NewAuthorService(authorRepository)
	authorHandler := author.NewAuthorHandler(authorService)
	return authorHandler
}
