// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"gobook/src/user/delivery/http"
	user2 "gobook/src/user/repository"
	user3 "gobook/src/user/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeUserHandler(db *gorm.DB) *user.UserHandler {
	userRepository := user2.NewUserRepository(db)
	userService := user3.NewUserService(userRepository)
	userHandler := user.NewUserHandler(userService)
	return userHandler
}
